trigger: none

resource:
  pipelines:
    - pipeline: BuildPipeline
      source: 03-build-and-deploy-to-selected

stages:

  - stage: Deploy_To_PRD
    jobs:
      - job: Deploy_To_PRD
        steps:
          - download: BuildPipeline
          - script: echo "Deploy to PRD environment..."
