trigger: none

resources:
  pipelines:
    - pipeline: BuildPipeline
      source: 03-build-and-deploy-to-selected

stages:

  - stage: Deploy_To_DEV
    jobs:
      - job: Deploy_To_DEV
        steps:
          - download: BuildPipeline
          - script: echo "Deploy to DEV environment..."
